# Modeled off of godot-cpp https://github.com/godotengine/godot-cpp/blob/master/.github/workflows/ci.yml

name: 🛠️ Build All
on: 
#    push:
#        branches: [ main ]
    pull_request:
        paths: [ '**' ]
    workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.name }} ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        identifier: [linux, windows, macos, ios, android-arm32, android-arm64, web-nothreads]
        target: [debug, release]
        include:
          - identifier: linux
            platform: linux
            name: 🐧 Linux
            runner: ubuntu-22.04
            flags: arch=x86_64
            
          - identifier: windows
            platform: windows
            name: 🪟 Windows
            runner: ubuntu-22.04
            flags: arch=x86_64

          - identifier: macos
            platform: macos
            name: 🍎 macOS
            runner: macos-latest
            flags: arch=universal

          - identifier: ios
            platform: ios
            name: 🍏 iOS
            runner: macos-latest
            flags: arch=universal

          - identifier: android-arm32
            platform: android
            name: 🤖 Android Arm32
            runner: ubuntu-22.04
            flags: arch=arm32

          - identifier: android-arm64
            platform: android
            name: 🤖 Android Arm64
            runner: ubuntu-22.04
            flags: arch=arm64

          - identifier: web-nothreads
            platform: web
            name: 🌐 Web No-threads
            runner: ubuntu-22.04
            flags: threads=no

    steps:
      - name: Checkout Map Generator
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Setup Base Dependencies
        uses: ./.github/actions/base-deps
        with:
            platform: ${{ matrix.platform }}

      - name: Setup Build Cache
        uses: ./.github/actions/build-cache
        with:
          cache-name: ${{ matrix.identifier }}-${{ matrix.target }}
        continue-on-error: true

      - name: Build
        env:
            SCONS_CACHE: "${{ github.workspace }}/.scons-cache/"
            TARGET: 'template_${{ matrix.target }}'
        shell: sh
        run: |
            scons -C godot target=$TARGET platform='${{ matrix.platform }}' ${{ matrix.flags }} debug_symbols=no -j2

      - name: Strip Libraries (Windows)
        if: ${{ matrix.platform == 'windows' }}
        shell: sh
        run: |
          cd godot
          strip volume-shader/addons/volume_shader/bin/libvolume_shader.${{ matrix.platform }}.${{ matrix.target }}.*.dll
          ls -l volume-shader/addons/volume_shader/bin/

      - name: Strip Libraries (Linux)
        if: ${{ matrix.platform == 'linux' }}
        shell: sh
        run: |
          cd godot
          strip volume-shader/addons/volume_shader/bin/libvolume_shader.${{ matrix.platform }}.${{ matrix.target }}.*.so
          ls -l volume-shader/addons/volume_shader/bin/

      - name: Include Files
        shell: sh
        run: |
          cp '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE.txt' ${{ github.workspace }}/godot/volume-shader/addons/volume_shader/

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: volumeShader-${{ matrix.identifier }}-${{ matrix.target }}
          path: |
            ${{ github.workspace }}/godot/volume-shader/

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          include-hidden-files: true
          name: ${{ github.event.repository.name }}
          pattern: volumeShader-*
          delete-merged: true